### ISSUE TITLE
Python strftime() does not work

### ISSUE THREAD

**Issue by gorideyourbike** [replit/repl.it#100]
I am having issues with this block of code.

```python
import datetime

now = datetime.datetime.now()
print now.strftime('%A')
```

In repl.it, an empty string is returned. However the Python CLI () on my computer returns ```'Tuesday'```.

**Comment by amasad** [comment]
This should work on our Python3 implementation http://repl.it/languages/Python3
We're no longer going to maintain this project as we're moving the language sandboxes to the server for a better user experience, we do have an API if you're interested http://repl.it/api
