### ISSUE TITLE
[python] Weird math calculation

### ISSUE THREAD

**Issue by zhouzhuojie** [replit/repl.it#103]
Repl python may have some floating point issues derived from Javascript:

![screenshot_052014_013747_pm](https://cloud.githubusercontent.com/assets/658840/3030843/bbebdae0-e045-11e3-9790-a22e3f16ed8f.jpg)

Below is the result from a native python env:

![screenshot_052014_014114_pm](https://cloud.githubusercontent.com/assets/658840/3030859/e5bf2cdc-e045-11e3-9e51-8d68bab0fcc5.jpg)

**Comment by amasad** [comment]
This should work on our Python3 implementation http://repl.it/languages/Python3
We're no longer going to maintain this project as we're moving the language sandboxes to the server for a better user experience, we do have an API if you're interested http://repl.it/api

**Comment by nlitsme** [comment]
Maybe you could disable the broken python2 implementation, it is still the front page of repl.it.

I find it rather strange that you keep active a broken python implementation active for more than one year. Note also, that your site one of the top google hits, when googling for 'run python online'. So you will let quite a few people fail their online python experimentation.

**Comment by amasad** [comment]
@nlitsme A lot of people depend on it. But you're right we should hide it from the front page. 

However, when people land on the site the first thing they see is python3 and from our data analytics, it's obvious that most people are starting to use Python3.
