### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by casamajor** [replit/repl.it#110]
![repl it testing 2](https://cloud.githubusercontent.com/assets/8076939/3532176/b7a78954-07b7-11e4-907f-ba6da11325d5.jpg)
Hi,

I am new to repl.it, node.js and most of the other libraries it is built on. Could you please let me know how to deploy the editor + console onto my website?

I have installed node.js, npm, CoffeeScript and Pygments successfully and then copied and updated the whole https://github.com/replit/repl.it from GIT into my web dir (/repl.it).

I am now just trying to replicate what you have on http://repl.it/languages/Python. I included the CSS and js files:

    
    <link type="text/css" rel="stylesheet" href="/assets/repl.it/css/style.css" />
    <link type="text/css" rel="stylesheet" href="/assets/repl.it/css/print.css" media="print" />
    <link type="text/css" rel="stylesheet" href="/assets/repl.it/css/ansi.css" />
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="/assets/repl.it/jsrepl/jsrepl.js" id="jsrepl-script"></script>
    <script src="/assets/repl.it/repl.it.js"></script>
    <script src="/assets/repl.it/lib/ace/ace.js"></script>

And then the html for the editor and the console:

    <div id="editor" style="width: 528px; height: 358px;">
    ...
    </div>
    <div id="resize-center" style="left: 528px;"></div>
    <div id="console" style="width: 528px; height: 358px;">
    ...
    </div>

However, even though I am testing it on an isolated view (in order to avoid any interference with my own CSS), the editor and the console are not rendered properly, the editor is full of ÂÂÂÂÂÂÂÂÂÂ chars and the console is not working (please see screenshot attached).

I am not sure whether I should call jsrepl.js and repl.it.js, which you use but are not in the GIT repo, or /repl.it/jsrepl/sandbox.js and /repl.it/server.js instead.

Is there anything else I should do for it to work?

Thanks!

Agustín

**Comment by amasad** [comment]
We're no longer going to maintain this project as we're moving the language sandboxes to the server for a better user experience, we do have an API if you're interested http://repl.it/api
