### ISSUE TITLE
ImportError: No module named select

### ISSUE THREAD

**Issue by jkennethcarino** [replit/repl.it#111]
When I tried to import subprocess, it raise an error: No module named select

Python 2.7.2 (default, Jul 20 2011, 02:32:18)
[GCC 4.2.1 (LLVM, Emscripten 1.5, Empythoned)] on linux2

> > > import subprocess
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/lib/python2.7/subprocess.py", line 429, in <module>
> > >     import select
> > > ImportError: No module named select

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)

Also, this has been fixed :)
