### ISSUE TITLE
[Python] Strings are getting messed up.

### ISSUE THREAD

**Issue by dabura667** [replit/repl.it#112]
decoding hex strings in python is causing improper binary strings to be created... I thought maybe the data was just being shown in my browser differently, but I tried hashing, and it seems that data is getting garbled somehow.

![issue11111](https://cloud.githubusercontent.com/assets/6586275/3625598/c44517e0-0e6e-11e4-84c6-149a2a5dea45.PNG)

On a related note, the other day typing in just the string '7' for some reason returned the binary string for 7 in ascii. Also capital 'E' was doing the same. a binary string of the byte in ascii was returned instead of just 'E' being returned.

I am on a Japanese version of Windows 7 64 bit, and my browser is Chrome, set to Japanese language.

Any advice / help would be appreciated. Thanks

**Comment by amasad** [comment]
This is now fixed if you use Python3 http://repl.it/languages/Python3
We're no longer going to maintain this project as we're moving the language sandboxes to the server for a better user experience, we do have an API if you're interested http://repl.it/api
