### ISSUE TITLE
[Ruby] Inline ifs not working correctly

### ISSUE THREAD

**Issue by SomeRed** [replit/repl.it#113]
Hello,Awesome work on repl.it
When you write something like 'print(5) if true || false' the Ruby interpreter still waits for an 'end' keyword,inline ifs don't need it.
example code:
def fact(n)
return 1 if n == 0;
fact(n-1)*n
end

**Comment by amasad** [comment]
This works fine now on our Ruby 2 implementation
We're no longer going to maintain this project as we're moving the language sandboxes to the server for a better user experience, we do have an API if you're interested http://repl.it/api
