### ISSUE TITLE
Lua not giving error with only one word as input

### ISSUE THREAD

**Issue by DealerNextDoor** [replit/repl.it#116]
This really isn't a big issue, but if you go to the lua engine and just type in one word and try to run the code, it doesn't give the standard `input:1: syntax error near <eof>` output. 

So just running:

```
asdf
```

regardless of the whitespace won't produce an error. I realize not running actual code defeats the purpose, but just saying, maybe some other errors get suppressed too?

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)

And also, this has been fixed :)
