### ISSUE TITLE
Lua hex values not working

### ISSUE THREAD

**Issue by Rochet2** [replit/repl.it#117]
Language: Lua
Code: `print(0x1)`
Output: `[string "stdin"]:1: malformed number near '0x1'attempt to call a nil value`

http://repl.it/1ko/2

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)

Also, this has been fixed :)
