### ISSUE TITLE
Adding Debugger for Ruby

### ISSUE THREAD

**Issue by mperejda** [replit/repl.it#118]
Can a user manually implement a debugger with the existing build of repl.it for ruby? 

Could it be built into the existing project? Thinking of forking and making an integration but don't know where to start. Thanks!

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)
