### ISSUE TITLE
Clear console from editor textbox

### ISSUE THREAD

**Issue by deostroll** [replit/repl.it#122]
On windows it ctrl+k. However, while typing code in the editor textbox, it does not work. It only works once we are active on the shell, (I.e when we want to type directly in the shell).

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)
