### ISSUE TITLE
Lua REPL Problems

### ISSUE THREAD

**Issue by TULOA** [replit/repl.it#124]
Ok So I got a couple for you. The first is the return of the "ERROR: ON NON-WEBKIT BROWSERS CONNECTION TO THE SERVER IS NEEDED FOR INPUT" message.

I generally only see that one after it sits for a bit. I am sure a fine tune should fix this for you guys.

The next is when you run the sample program resaved: http://repl.it/5ot
You will see it run fine. Enter something twice fast and it hook spams down.
Not sure on this one.
Tried just now to reproduce and the REPL and page refreshed like it crashed.

**Comment by skyem123** [comment]
I've just run into this error.
To reproduce this bug, run https://repl.it/BQUu and leave it for some time.
Eventually, the `ERROR: ON NON-WEBKIT BROWSERS CONNECTION TO THE SERVER IS NEEDED FOR INPUT` message starts to get printed.

In general input for Lua tends to hang and makes the webpage pop up a dialog box saying that "this program is taking too long to finish" when I try to type things in.
