### ISSUE TITLE
String Functions

### ISSUE THREAD

**Issue by TULOA** [replit/repl.it#125]
Noticing most functions that worked like for example:

```
test = "hi"
test.find("hi") --Returns 1
```

Does not... It errors stating that it doesnt have the right amount of arguments. So you have to call it like:

```
String.find(test, "hi") -- Returns 1.
```

Such that you have to use:

```
test.find(test, "hi")
```

Just seems like a bit more typing since it should be available natively.

In short:
test.find("hi") should work and not force us to use test.find(test, "hi")

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
