### ISSUE TITLE
Python is broken in the `master` version

### ISSUE THREAD

**Issue by Maratyszcza** [replit/repl.it#128]
Python does not work with the `master` version of repl.it
When I choose Python, the progress bar stalls in beginning, and JS log shows the message:
`Uncaught ReferenceError: output is not defined` (Chrome) or `ReferenceError: output is not defined` (FireFox). The error originates from line 107 in jsrepl/sandbox.js (this is a call to eval).

It seems to get broken recently: I have a earlier copy of repl.it repository (last commit: `646b69f4fe04a8aa98bd08b96bde92ac96e2a538`, Fri Dec 12 22:07:19) where Python works fine.

The problem is Python-specific, other languages seem to work.

**Comment by amasad** [comment]
JSRepl is a good place to start looking into this problem https://github.com/replit/jsrepl
We're no longer going to maintain this project as we're moving the language sandboxes to the server for a better user experience, we do have an API if you're interested http://repl.it/api

**Comment by abhishekgupta92** [comment]
@Maratyszcza - Could you figure this out? I am facing the same problem. Thanks in advance for replying :)

**Comment by Maratyszcza** [comment]
@abhishekgupta92 I didn't find how to fix repl.it Python interpreter, but I figured out how to build the CPython interpreter for asm.js. See https://github.com/PeachPy/EmCPython
