### ISSUE TITLE
Signup being posted using GET request?

### ISSUE THREAD

**Issue by gbraad** [replit/repl.it#131]
The following form:

``` html
          <form id="signup-form">
            <div> <input name="username" type="text" required="required" placeholder="Username"></div>
            <div> <input name="email" type="text" required="required" placeholder="Email"></div>
            <div> <input name="password" type="password" required="required" placeholder="Password"> </div>
            <button class="button">Sign up</button>
          </form>
```

uses signupHandler which does a post. However, in the browser I can see the following url

```
repl.it/signup?username=[username]&email=[email]&password=[plaintext password]
```

which is going to be cached.

```
Request URL:http://repl.it/signup?username=blaha&email=blah%40blah.blah&password=blahbla
Request Method:GET
Status Code:200 OK
Host:repl.it
Referer:http://repl.it/signup?username=blah&email=bla@bla.bla&password=dsds
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
Query String
username:blaha
email:blah@blah.blah
password:blahbla
```

**Comment by amasad** [comment]
I'll update the form to be a post, but I don't understand how it would produce a get request if it was `preventDefault()`ed and sent as an AJAX post.
What browser are you using?

**Comment by gbraad** [comment]
The browser info was in the bugreport as USER AGENT, but it was Chrome 40
on Linux x64... It could very well be a browser bug. However, this was the
only page for which this error seemed to have occurred so far.

On Wed, Feb 25, 2015 at 3:14 AM, Amjad Masad <notifications@github.com>
wrote:

> I'll update the form to be a post, but I don't understand how it would
> produce a get request if it was preventDefault()ed and sent as an AJAX
> post.
> What browser are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/replit/repl.it/issues/131#issuecomment-75824505>.
>



-- 
Gerard Braad — 吉拉德
   F/OSS & IT Consultant in Beijing
   http://gbraad.nl  gpg: 0x592CFE75

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
