### ISSUE TITLE
Python 2.7 hashlib generates identical hash

### ISSUE THREAD

**Issue by samrad** [replit/repl.it#133]
Hi,

For some reason, generating two SHA512 hashes for different strings gives two identical results. Here is the code and screenshot:

```python
import hashlib

one = hashlib.sha512("hey").hexdigest()
two = hashlib.sha512("yo").hexdigest()
print one == two   # prints True
```

![hashlib-bug](https://cloud.githubusercontent.com/assets/2217027/6548621/387d83cc-c5bc-11e4-88c4-9f557d2bddd6.png)

**Comment by amasad** [comment]
Yes the problem comes from incompatibility with JS number type. You can use python3

**Comment by samrad** [comment]
Alright. Thanks.

**Comment by amasad** [comment]
No problem here is a direct url: http://repl.it/languages/Python3
