### ISSUE TITLE
APL examples not displaying correctly in Chrome under Windows

### ISSUE THREAD

**Issue by garudajava** [replit/repl.it#134]
Don't know if this is something to report to Google, Microsoft, or here, but anyway, noticed some of the special characters in the APL examples (right in the first one for example, Conway's Game of Life), characters like rho and iota, don't display correctly on Chrome under Windows 8.  They did display correctly (as far as I can tell, not really fluent in APL) under IE.  Tried switching extensions off under Chrome but that didn't help.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
