### ISSUE TITLE
Option to sign in with Github and save files as gists

### ISSUE THREAD

**Issue by harshays** [replit/repl.it#135]
In addition to saving files on repl.it, Github can be used save and retrieve gists

**Comment by amasad** [comment]
working on it :)

**Comment by harshays** [comment]
If you could give me some kind of a direction, I'd like to work on it as well!

**Comment by amasad** [comment]
Actually, some of this work is not done in this repo, the open source and the not-open-source version fell out of sync and we moved a lot of the work to the backend and haven't got around to fix all this. If you're still interested in helping out, I'm sure we can figure out something. Please email me amjad.masad@gmail.com and we can talk more

**Comment by masad-frost** [comment]
We've added a way to save sessions as gists a while ago. You can either do it from your workspace (first gif), or from your sessions page (second gif). We will look into signing with Github soon. Thank you

![Share from workspace](https://cloud.githubusercontent.com/assets/1994028/11812167/f1bd7d42-a342-11e5-8920-c19f47559006.gif)

![share from sessions page](https://cloud.githubusercontent.com/assets/1994028/11812163/ea0d2c1e-a342-11e5-92cc-2cd37c489966.gif)
