### ISSUE TITLE
[Lua]Reading input

### ISSUE THREAD

**Issue by SomeRed** [replit/repl.it#136]
This code gives an error:
```lua
a = io.read'*number' -- read a number from stdin
print(a+1);
```
Looks like the function io.read returns before reading the number from stdin.

**Comment by masad-frost** [comment]
We don't support `io.read("*number")` but you can do `tonumber(io.read())` which results in the same output. The only difference is the intermediate step of converting string to number, but that's a very very trivial performance issue.
