### ISSUE TITLE
trying to load site over https and none of the links work

### ISSUE THREAD

**Issue by NullVoxPopuli** [replit/repl.it#138]
I was trying to embed a ruby snippet in a blog, and it was saying it was loading an insecure script.
I navigated to https://repl.it and upon clicking anything, nothing happens :-\

Using Chrome on Windows 8

**Comment by amasad** [comment]
Thanks for the report. Working on it. It now partially works. I should get it working by tomorrow.

**Comment by amasad** [comment]
This is now fixed. When you click 'share' on repl.it it should give you a protocol relative url, e.g. `//repl.it/embed/iyv.js` and then that should just work on your http(s) site. Here is a jsfiddle with https enabled and an embed. Let me know if that works for you.

https://jsfiddle.net/atLs4L8g/
