### ISSUE TITLE
PHP classes throw "can't be redefined" errors

### ISSUE THREAD

**Issue by MidnightLightning** [replit/repl.it#139]
If have a class in your script and run your script twice, it complains that you class can't be redefined; it seems to not clear the memory of that class from the console. Which is good for a REPL environment, but doesn't follow expected PHP behavior. Can we either change that behavior, or add a "clear user-defined classes" button, so re-running user scripts doesn't error out after the first run?

**Comment by masad-frost** [comment]
This is now fixed as we've changed the way the workspace behaves in that matter. Running from the editor now resets into a fresh environment. On the other hand, running any code from the console will not and will maintain your definitions, until it's reset.
