### ISSUE TITLE
Ruby: `"foo".class.name` doesn't work in console; does when run as script

### ISSUE THREAD

**Issue by RobertAKARobin** [replit/repl.it#140]
Typing `"foo".class` in the console makes it hang. However, it executes as expected when run as a script.

**Comment by RobertAKARobin** [comment]
Correction: `"foo".class` *does* work in the console, but it prompts for additional user input.

**Comment by masad-frost** [comment]
I think I found the issue here. The console is expecting `"foo".class` to be a class block opener, as opposed to the `.class` method. However, it should work fine if you hit enter twice, so this is just an input issue and nothing to do with the interpreter.

Shouldn't be too hard to fix.
