### ISSUE TITLE
Copy/Cut/Paste within repl.it not working in Safari Version 8.0.7 (10600.7.12)

### ISSUE THREAD

**Issue by zshnr** [replit/repl.it#142]
Hey! 

While using `repl.it` to test some JS code, I realized that I couldn't copy/paste or cut/paste from `repl.it` to `repl.it` or to applications outside of it. I can paste to the repl from any external source or browser tab just fine.

This is only happening on `Safari Version 8.0.7 (10600.7.12)`. The repl works fine in Chrome and FF. 

Is this a known bug?

Thanks!

**Comment by amasad** [comment]
cc @masad-frost, can you verify?

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
