### ISSUE TITLE
repl.it Python 3 enhancement - Make "locals()" to output less unwanted stuff

### ISSUE THREAD

**Issue by build2master** [replit/repl.it#143]
The issue:

Open "repl.it" for Python 3. Execute "locals()" or "globals()" in the command prompt. It list a lot of stuff out. Not helpful when I want to remind myself of what variables is there.

I am guessing you just preload all the require classes libraries you need to handle the server connection on a Python terminal? One possible solution might be to sandbox the terminal that we are actually using?

**Comment by amasad** [comment]
@masad-frost can you take a look at this and log at the goval repo?

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
