### ISSUE TITLE
Ability to add title and tags to saved sessions.

### ISSUE THREAD

**Issue by jwjb** [replit/repl.it#145]
For organizational reasons a nice to have feature would be the ability to add title and tags to saved sessions like what is available using [Ideone](http://ideone.com/).

**Comment by masad-frost** [comment]
This is available on the new sessions page.

Current features: 
- Add title to sessions
- Add tags to sessions
- Share session
- Delete from sessions page

Soon to follow: 
- filter
- search

[Check it out](https://repl.it/sessions)

**Comment by jwjb** [comment]
Thanks, all looks great where I especially love the title, tags and search features.
