### ISSUE TITLE
Python not working.

### ISSUE THREAD

**Issue by HotFireyDeath** [replit/repl.it#146]
When I open a new Python project (or load an existing one), the console never loads properly (stays at loading bar).

**Comment by TechMasterAllen** [comment]
This also happens to me. What browser are you using? I'm using chrome on an acer c720 chromebook.

**Comment by lombas** [comment]
It's fine for me, in two different computers (W8 and W10, both in chrome)
Does the problem still occurs? If not, can you close the issue? I'm learning about git.

**Comment by HotFireyDeath** [comment]
Okay. The problem is no longer there, so I assume it has been fixed. Thanks.

**Comment by amasad** [comment]
yup fixed it :)
