### ISSUE TITLE
Web page not working

### ISSUE THREAD

**Issue by danieltanfh95** [replit/repl.it#147]
![image](https://cloud.githubusercontent.com/assets/2587165/10664374/71cb0d42-78f5-11e5-91fc-cf0b8ff413f2.png)

ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by amasad** [comment]
It's working fine for me. Seems like an issue in windows. See http://answers.microsoft.com/en-us/ie/forum/ie11-windows_7/errsslversionorciphermismatch/567fd181-7a27-48c5-95d1-b3095df255ec?auth=1

**Comment by Shadowys** [comment]
So it's due to the site not using the latest SSL certificate ? o.O Then I can't use to site to spread code since not all of them can deal with this.

**Comment by amasad** [comment]
ah it seems that it's because you're using an old OS and our certificate provider doesn't support. See https://www.cloudflare.com/ssl
I'll see if I can fix this

**Comment by smLocal** [comment]
repl.it is having an issue today for me on mac yosemite and pc windows 8.
its adding extra characters.

**Comment by amasad** [comment]
@smLocal can you add a screenshot?

**Comment by smLocal** [comment]
just tried again and it is working fine. weird

**Comment by smLocal** [comment]
hey thank you amasad!
