### ISSUE TITLE
Auto next line and auto indent after pressing enter after function definition in Python

### ISSUE THREAD

**Issue by lombas** [replit/repl.it#148]
In Python language pressing "enter" after writing a definition function line tries to execute the code instead of going to next line, auto indent and waiting for following lines of code.

The expected behavior is present on the Python 3 language but not in Python  language on repl.it console.
I know that I can use "shift+enter" to get a new line and then use "tab", but it's way easier when it's automatically

Could this behavior be implemented on Python? Thnks

![py3](https://cloud.githubusercontent.com/assets/898124/10773150/f444dc78-7ce0-11e5-9b07-446d7dd89916.jpg)
![py2](https://cloud.githubusercontent.com/assets/898124/10773151/f448ee30-7ce0-11e5-879d-f63d4f6a00bc.jpg)

**Comment by amasad** [comment]
@masad-frost can you take a look when you have a chance.

**Comment by masad-frost** [comment]
@amasad  looks like the behavior has been scrapped even for other languages that previously had it after the latest refactor.

**Comment by masad-frost** [comment]
Shipping an update soon that adds this behavior to the following languages: 

- Python3
- Python 
- Ruby
- APL
- Bloop
- JavaScript
- Lua
- Roy
- Traceur (es6)
- Unlambda
- CoffeeScript
- Emoticon
- Kaffeine
- Move
- Brainfuck
- Forth
- Scheme
- LOLCODE
- QBasic 

@lombas Thanks for the heads up. I'll let you know when it's out. Closing
