### ISSUE TITLE
repl.it is not safe

### ISSUE THREAD

**Issue by SoniEx2** [replit/repl.it#149]
So I like to hash my passwords but apparently repl.it sends my passwords to the server.

What happened to this? "All code processed by repl.it runs entirely on your computer, with no server-side evaluation. It uses language interpreters written in JavaScript to execute your code and keep track of state. Some of the interpreters (like BiwaScheme) are originally implemented in JavaScript, while others (like Python) were compiled from their original lower-level implementations using Emscripten."

You're clearly using websockets (because I used a websocket debugger).

**Comment by amasad** [comment]
yeah, we had to change this but forgot to change the copy. We're not saving the code if that's any consultation.

**Comment by SoniEx2** [comment]
It's a shame I can't use repl.it to hash my passwords anymore.

It's also a shame there's no alternative for local, in-browser interpreters.

**Comment by amasad** [comment]
JavaScript is still local

**Comment by SoniEx2** [comment]
1 out of ~25?

**Comment by amasad** [comment]
Not really: it's Lua, Scheme, everything under Web, and everything under
Esoteric. So more than half ;)
The problem is that chrome broke my app so I had to switch to server side
execution.

**Comment by SoniEx2** [comment]
So what if you use PNaCl on chrome?
