### ISSUE TITLE
Remember history in localStorage/cookie

### ISSUE THREAD

**Issue by max99x** [replit/repl.it#15]
It would be nice to remember the last few commands entered in the REPL in localStorage/cookie. This is not only useful for users, but also helps for debugging, since one often executes the same command again and again and refreshes between the tries while tweaking the engine.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)
