### ISSUE TITLE
Node on repl.it is obsolete

### ISSUE THREAD

**Issue by rsp** [replit/repl.it#150]
The version of Node.js on repl.it is 0.12.0 with V8 version 3.28.73.0.
The latest stable Node version is 5.0.0 with V8 version 4.6.85.28.
The latest version with Long Term Support is 4.2.2 with V8 4.5.103.35.

The biggest problem is the ES6 support: https://repl.it/BZRs
The same works fine with plain JavaScript: https://repl.it/BZRq

More info::
* https://nodejs.org/en/download/releases/
* https://github.com/nodejs/node/blob/master/CHANGELOG.md

What are the plans to upgrade Node on repl.it?

**Comment by masad-frost** [comment]
Node has been updated to v5.0.0

This should work fine https://repl.it/BZRs/1

**Comment by rsp** [comment]
@masad-frost Great. Thanks a lot!

**Comment by masad-frost** [comment]
I'd love to take credit but it was @amasad :santa: that shipped it. Thank you for reporting this. Keep us posted for any bugs or feature requests.

**Comment by rsp** [comment]
@masad-frost Thanks for the info. @amasad Thanks for the upgrade! Best regards.
