### ISSUE TITLE
All shared/saved programs are empty

### ISSUE THREAD

**Issue by rsp** [replit/repl.it#151]
**I noticed it today. I don't know if someone can confirm it. All shared repl.it URLs are now empty.**

All loaded programs appear to be empty or contain the boilerplate code in the case of Java. This is the case with both newly created programs and old ones.

It affects all languages on repl.it that I tested and happens on Chromium and Firefox.

More info:

When I write a new program and click Share, the url changes to something like https://repl.it/B1Lg but when I reload the page the code disappears. When I write something again and click Save, the url changes to https://repl.it/B1Lg/1 but the code still disappears after reload. But there is no error about session not found like is the case with https://repl.it/B1Lg/1000 so the sessions seems to be saved but either it is saved empty or there is a problem with loading it.

It also affects old programs that used to work in the past like https://repl.it/BZZS

**Comment by amasad** [comment]
This should be fixed now, let me know if otherwise

**Comment by rsp** [comment]
@amasad It seems to work now. Thanks a lot.

By the way - great service. Currently it is my favorite way to share simple code examples with people, especially that I can compare examples in different languages. Can I help in any way to update the version of Node.js? See issue #150 Thanks.
