### ISSUE TITLE
importing doesn't seem to work in python

### ISSUE THREAD

**Issue by tindrew** [replit/repl.it#158]
I've been trying to run this code: 

from sys import argv

script, first, second, third = argv

print "The script is called:", script
print "Your first variable is:", first
print "Your second variable is:", second
print "Your third variable is:", third

but when I do, I get this error:

Traceback (most recent call last):
  File "python", line 3, in <module>
ValueError: need more than 1 value to unpack

I assume it's because in order to run it, I need to run the .py as:

example.py script first second third

but I'm not 100% sure because I'm new to both python and programming.

**Comment by amasad** [comment]
argv would be used from the command line, in this case use `input`
