### ISSUE TITLE
Some session settings do not save.

### ISSUE THREAD

**Issue by ryanpcmcquen** [replit/repl.it#160]
Or rather, are not remembered. For instance `indent type` always gets set back to `tabs`, even though I have set it to `spaces`.

![screen shot 2016-05-02 at 12 00 34 pm](https://cloud.githubusercontent.com/assets/772937/14964582/a34ca47a-105d-11e6-8b12-c11ac448f99e.png)

**Comment by amasad** [comment]
They're saved on per browser basis (local storage) but not on the server per user basis. We'll fix that.

**Comment by ryanpcmcquen** [comment]
Thank you!

**Comment by amasad** [comment]
This has been fixed for a while btw

**Comment by ryanpcmcquen** [comment]
Thank you!
