### ISSUE TITLE
My code was deleted

### ISSUE THREAD

**Issue by Ethan15457** [replit/repl.it#163]
So I was working on the code then 30 minutes later I couldn't find it. Not even get into my sessions. I get this error code. "Something went wrong!" in red. Help?

**Comment by amasad** [comment]
Where do you get this error? On the sessions page?What is the email
associated with your account? If you're not comfortable sharing here then
please email us at contact@repl.it

**Comment by Ethan15457** [comment]
@amasad I had it working not that long ago. I get the error when I go to the sessions page and try to see my saved copies. The Email that I use with the account is 

ethan15457@waitakerecollege.school.nz

**Comment by amasad** [comment]
This should be fixed now. Can you verify?

**Comment by Ethan15457** [comment]
@amasad Yeah man. Big thanks for fixing it
