### ISSUE TITLE
Ruby (and possibly others) won't load on Firefox Developer Edition

### ISSUE THREAD

**Issue by puck7744** [replit/repl.it#164]
This issue has been happening to me for a while but since I noticed it's still not solved I thought I should file a report.

When I go to repl.it and choose any language I get a Javascript error: f is undefined at `main.bundle.js:52:6896`

I'm currently using Firefox Developer Edition 49.0a2. If I load the same page on Chrome everything works fine. Native Javascript seems to work on Firefox, but C# and Python also didn't want to load (though with different errors)

**Comment by amasad** [comment]
Thanks for reporting! I found an error -- but that wasn't blocking the usage of the site -- and I fixed it. Can you please check if it's fixed? I'm testing on FF 47.0.1 -- maybe it's a developer edition problem?

**Comment by puck7744** [comment]
Thanks for the quick reply! I gave Ruby another try and it didn't give an error this time, but it doesn't load either. The yellow "Connecting to server..." message hangs around forever and the progress bar in the right pane continuously fills up and resets.

Nothing alarming came through in the console. If it helps any here's the full log:
```
GET https://repl.it/languages/ruby [HTTP/2.0 200 OK 128ms]
GET https://fonts.googleapis.com/css [HTTP/2.0 200 OK 33ms]
GET https://repl.it/public/css/print.css [HTTP/2.0 304 Not Modified 33ms]
GET https://repl.it/public/ace/ace.js [HTTP/2.0 304 Not Modified 69ms]
GET https://repl.it/public/jsrepl/jsrepl.js [HTTP/2.0 304 Not Modified 26ms]
GET https://repl.it/public/main.bundle.js [HTTP/2.0 304 Not Modified 57ms]
GET https://repl.it/public/images/logo-small.png [HTTP/2.0 304 Not Modified 80ms]
GET XHR https://repl.it/is_authenticated [HTTP/2.0 304 Not Modified 186ms]
GET XHR https://repl.it/is_authenticated [HTTP/2.0 200 OK 189ms]
GET XHR https://repl.it/is_authenticated [HTTP/2.0 200 OK 121ms]
GET XHR https://repl.it/public/ace/mode-ruby.js [HTTP/2.0 200 OK 45ms]
GET https://connect.facebook.net/en_US/sdk.js [HTTP/2.0 200 OK 0ms]
GET https://eval.repl.it/ws [HTTP/1.1 101 Switching Protocols 110ms]
GET https://staticxx.facebook.com/connect/xd_arbiter/r/bz-D0tzmBsw.js [HTTP/2.0 200 OK 0ms]
GET https://productpains.com/suggestionBox.html [HTTP/1.1 200 OK 0ms]
GET https://productpains.com/js/lib/floatingResizer.min.js [HTTP/1.1 304 Not Modified 40ms]
GET https://productpains.com/SuggestionBoxBundle.js [HTTP/1.1 304 Not Modified 52ms]
GET XHR https://productpains.com/api/getProductWithConfig [HTTP/1.1 200 OK 60ms]
GET XHR https://productpains.com/api/getLoggedInUser [HTTP/1.1 200 OK 53ms]
```

**Comment by amasad** [comment]
Can you look at the websocket connections? It's under `other` tab under the network tab.
Are you behind a firewall?

**Comment by puck7744** [comment]
I have a direct connection with no firewalls enabled. I examined the websocket connection and this is the data that was sent through:
```
>> {"command":"auth","data":"[REDACTED]"}
<< {"command":"auth_result","data":"true","error":""}
>> {"command":"select_language","data":"ruby"}
<< {"command":"ready","data":"","error":""} 
```
Seems that there's no trouble there, unless there should be more to it than what I'm seeing. Maybe the client side script isn't noticing the event for some reason?

**Comment by amasad** [comment]
Looks like you're connected -- hmm that's weird. Thanks for debugging with me -- can I ask you to try the regular Firefox as opposed to the developer edition?

**Comment by puck7744** [comment]
No problem! This is my day job so I'm pretty used to it. I don't typically use vanilla Firefox anymore, but I downloaded a fresh copy of 47.0.1x64 and ran it under a new profile. Everything worked without a hitch. I suppose it must be something they changed between 47 and 49. For now I'll just use a different browser with repl.it, but hopefully you can figure it out before this change goes live! :)

**Comment by amasad** [comment]
Great, thanks! If you can open a bug with Mozilla I'd be very grateful.

**Comment by Mihail-D** [comment]
Python3 enviroment won't load on Firefox 47, 48 and FF DE.
Fix it plz :)

**Comment by mpaunovic** [comment]
Strange, the latest version of Firefox (51.0.1 x64) crashes when opening repl.it no matter the language. Can anyone else reproduce this behavior? Thanks.

**Comment by seraku24** [comment]
Running FF 51.0.1 (32-bit) on Windows 10 (v1607).

I have been randomly getting hanging issues launching repl.it for JavaScript.  This completely locks the Firefox instance, requiring a forced quit.  What is odd is that Firefox usually can tell when a script is running too long and offer to stop it, but that never happens in this case.

**Comment by mpaunovic** [comment]
@seraku24 

That's exactly my problem with it, too.

**Comment by mdreier** [comment]
I am having the same problem as @mpaunovic and @seraku24 reported with Firefox hanging whenever I start a new JavaScript session.
Reproduction:

1.  Go to https://repl.it
2. Click on "Sessions"
3. Click on "New Session"
4. Select JavaScript

This completely hangs Firefox, i.e. the whole Application does not react anymore and has to be terminated.

Environment: Firefox 51.0.1 32 bit, Windows 10

**Comment by amasad** [comment]
Firefox keeps pushing regressions :/
Did anyone report to Mozilla?

**Comment by mpaunovic** [comment]
Just to let you know guys, with the latest Firefox update (52) everything works just fine. Go figure.

**Comment by amasad** [comment]
Great thank you! Alas this is not the only time Firefox randomly breaks
things between releases.
