### ISSUE TITLE
Can not write assignment instructions in plain markdown

### ISSUE THREAD

**Issue by niwolive** [replit/repl.it#167]
I haven't found a way to write instructions for an assignment in plain Markdown.

Has this been considered / thought through?

I'm keen to help make it happen, and pointers as to where to start would be appreciated.

**Comment by amasad** [comment]
Hey @fuzzytern this repo is old. Alas, the code for the classroom product is currently closed. We're thinking of ways to do open source parts of it. The markdown feature is on our todos

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
