### ISSUE TITLE
ImportError: No module named 

### ISSUE THREAD

**Issue by alkopop79** [replit/repl.it#168]
So far I get this error with any library I've tried to import. Kinda renders repl.it completely useless. 

```
Traceback (most recent call last):
  File "python", line 1, in <module>
ImportError: No module named 'graphics'
```

**Comment by amasad** [comment]
Are those libraries from pypi?

**Comment by amasad** [comment]
anyways we don't currently support graphics

**Comment by anshumanf** [comment]
Same with jsonpickle and sklearn which are both from pypi

**Comment by koolkalang** [comment]
It seems to be very particular. `import datetime` in lower case works, but `import DateTime` (which is what the libraries search inserts into the code) does not work. Nothing from the gif on this [blogpost](https://repl.it/site/blog/python-import) works either.

**Comment by RobbyDmz** [comment]
I'd like to add that for me this issue is very common on the 2.7 python environment.
I tried adding pydash and while it should be supported, the 2.7 environment keeps throwing the ImportError. The Python3 environment does not seem to have this issue.

I've experienced this with datetime, pydash and a number of other libraries.

**Comment by maxkoryukov** [comment]
I want to import this package: https://pypi.python.org/pypi/route4me-sdk , as you can see the name of the package -- `route4me-sdk` -- is not a valid python identifier, so I can't import. UI offers to use something like:

```python
import route4me-sdk # learn more: https://python.org/pypi/route4me-sdk
```

But, obviously, this doesn't work.

Is there a way to import a package with a name, which is not a valid python identifier (not `numpy` and `pydash`)?

**Comment by roll** [comment]
> I want to import this package: https://pypi.python.org/pypi/route4me-sdk , as you can see the name of the package -- route4me-sdk -- is not a valid python identifier, so I can't import.

Just run into. Not sure how to import modules containing dashes etc.

**Comment by TheNewJavaman** [comment]
This error still exists with Python 3.6 with keras (neural network, works with TensorFlow). Normally I would do
`import keras`
but the import UI tells me to use 
`import Keras`
Neither one works, as the output says that neither are valid modules.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
