### ISSUE TITLE
Mechanize library error 

### ISSUE THREAD

**Issue by sundharvs** [replit/repl.it#169]
The Mechanize library which is listed in the Python3 libraries section, raises this error - 

```
Traceback (most recent call last):
    File "python", line 1, in <module>
ImportError: No module named '_mechanize'
```
when I try to run 
```python 
import mechanize
```

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
