### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by daddadhad** [replit/repl.it#170]
I'm using python 2.7 with project mode.
It's even in the libraries screen yet it doesn't work:
`
Traceback (most recent call last):
`
`
File "main.py", line 1, in <module>
`
`
import requests # learn more: https://python.org/pypi/requests
`
`
ImportError: No module named requests
`
`
exited with non-zero status
`

Do you not support this module? If not then please take it off the list

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
