### ISSUE TITLE
Teacher Redirect Without Clear Editor Link

### ISSUE THREAD

**Issue by Christofosho** [replit/repl.it#173]
Hi there,

I signed up for a classroom account, and was hoping to use repl.it as an editor as well. I can't seem to locate an easy to access link to the editor, when I am logged into the classroom as a teacher. Upon hitting repl.it I am redirected to the teacher route, and do not see an easily accessible link back to the editor.

Edit: I see that the sessions link is meant to lead you back into the editor. This would probably be confusing for some individuals, and I think it would be excellent if there were a nice big link near the top for creating a new session (perhaps with alternate wording?).

Thank you,

Chris

**Comment by amasad** [comment]
Thanks Chris. We will make this better

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
