### ISSUE TITLE
[Scheme] Doesn't appear to output 0's

### ISSUE THREAD

**Issue by newswim** [replit/repl.it#174]
Given the following:

```scheme
(define (pascal row col)
    (cond ((> col row) 0)
    ((or (= col 0) (= col row)) 1)
    (else (+ (pascal (- row 1) (- col 1)) (pascal (- row 1) col)))))
  
(pascal 5 5)
```

We expect the output to be 0, but instead it's ` `.

If you surround the 0 in "'s `"0"`, it does print the case.

Any clue what might be causing this? Thanks!!

**Comment by amasad** [comment]
Hey, the bug is there and there is a fix coming out later today.

However, pascal's triangle doesn't have any zeros ;)

**Comment by newswim** [comment]
Fair enough :-]

Thanks!!!!
