### ISSUE TITLE
Attempting to disable infinite loop protection crashes Firefox

### ISSUE THREAD

**Issue by isiahmeadows** [replit/repl.it#175]
**Firefox version:** 53.0

1. Load JavaScript REPL
2. Attempt to disable infinite loop protection.
3. Firefox crashes 100% of the time.

**Comment by isiahmeadows** [comment]
Firefox bug, not repl.it bug

**Comment by amasad** [comment]
Was this fixed?

**Comment by isiahmeadows** [comment]
Nope. Just filed it here prematurely.

**Comment by amasad** [comment]
No worries. Did you file on Firefox? Would love to get a link to that

**Comment by isiahmeadows** [comment]
@amasad [Here](https://bugzilla.mozilla.org/show_bug.cgi?id=1347978).

I had to look it up.
