### ISSUE TITLE
Any plans to include NPM modules for Node sessions

### ISSUE THREAD

**Issue by cklanac** [replit/repl.it#177]
I see in your [post](https://repl.it/site/blog/npm) we can now require npm modules (that run the browser).  But are there plans to allow requiring modules in a node session. It would be great for teaching express along with the other common packages like bodyParser, cookieParser, morgan, winston, mongoose...

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
