### ISSUE TITLE
Login modal never loads. Page stuck on Loading

### ISSUE THREAD

**Issue by Alazilla** [replit/repl.it#178]
As above. On all Mac (Yosemite 10.10.4) machines in the classroom, across all browsers, we're getting the following:

![screen shot 2017-04-24 at 8 46 44 am](https://cloud.githubusercontent.com/assets/8107542/25340206/a65d71f4-28ca-11e7-97eb-d1d96d68f377.png)

Mobile version is still working, and Windows seems fine. This started last week, around Friday.

**Comment by amasad** [comment]
Hey @Alazilla this is now fixed. Sorry about that.

**Comment by darkplatinum** [comment]
Getting this problem now on my devices pls fix

**Comment by amasad** [comment]
@darkplatinum can you open the JavaScript console and tell me if you see any errors?

**Comment by darkplatinum** [comment]
I wont be able to because i am using ipad, it used to work but now doesnt. It stays stuck on loading on the home paage and on my repls. This works on the computer though.

**Comment by amasad** [comment]
@darkplatinum just checked on iPad and it seems to work. What's your username on Repl.it maybe something specific to your account?
Also do you know what version of iPad/

**Comment by darkplatinum** [comment]
ipad2: ios 9, ipad air 2: ios 10

Username: @YusufIbn

**Comment by darkplatinum** [comment]
It now is working thx for your help!:)
