### ISSUE TITLE
HTML file does not open

### ISSUE THREAD

**Issue by happyfatdog** [replit/repl.it#179]
the code shows up for a second, but then disappears immediately after, leaving me with a blank page

**Comment by amasad** [comment]
Are you sure you're on the right file? Please double check the file tab you're on

**Comment by happyfatdog** [comment]
i am sure i am on the right file. it also doesn't work when i start a new session.

**Comment by amasad** [comment]
Can you email us your account information so we can look at this? contact@repl.it

**Comment by happyfatdog** [comment]
Sent Information
