### ISSUE TITLE
Open, run, and modify existing projects or files

### ISSUE THREAD

**Issue by f0lie** [replit/repl.it#181]
This website is really useful to run python without spending too much time settings up things. However, I don't want spent time copying pasting code into the editor. I would really like to make the process of running and editing code as streamline as possible.

One possible feature is the ability to add links where a editor with preexisting code is imported. Some like `https://repl.it/languages/python3?include=link_to_code_here` or `https://repl.it/languages/python3?repo=link_to_github_repo`. The intend is to allow users to open a 'live experiment' and run the code themselves. Ideally, users run the code to see it works and modify it to understand it better. They could open a single file and code the interactively, showcasing why the python shell is useful. 

Adding folder hierarchies from repos maybe to be too complicated for the scope of the project. Adding single or multiple files seem to fit into the simple purpose though.

**Comment by amasad** [comment]
We have a `code` querystring would that work for now? [E.g.](https://repl.it/languages/python3?code=print(1))
We plain on having a closer integration with github soon.

**Comment by amasad** [comment]
we generally like to get feedback here: https://repl.it/feedback
