### ISSUE TITLE
Error loading web project environment repl.its 

### ISSUE THREAD

**Issue by benjaminEwhite** [replit/repl.it#183]
When logged in to repl.it and accessing some repl.its, some users get "Error loading language. Please try again". Below is a screenshot of the error log from Dev Tools:

![error-message](https://user-images.githubusercontent.com/960351/26893493-7cf0102e-4b89-11e7-8171-288ef3143714.jpg)

We use repl.it in our coding bootcamp program at Thinkful. This bug is effecting some but not all of our students. I am actually unable to reproduce it, but we have numerous reports.

It appears to only be triggered by the web project environment, and only when effected users are logged in to repl.it

**Comment by amasad** [comment]
Fixed will be deployed soon
