### ISSUE TITLE
Feature request - flag for hiding "run" button on embedded view

### ISSUE THREAD

**Issue by joshterrill** [replit/repl.it#184]
I know that this repo is no longer maintained, so this might not be the most appropriate place to put this. Nonetheless, I think it would be cool if there could be a flag on the share > embed option where when the embedded window is shown, it hides the "run" button.

This is what I was thinking.

A typical share code looks like this:

```
<script src="//repl.it/embed/{repl_id}/0.js"></script>
```

And when it's embedded looks like this:

![Imgur](http://i.imgur.com/YcBWyRn.png)

It would be cool to be able to do something like 

```
<script src="//repl.it/embed/{repl_id}/0.js?disableRun=true"></script>
```

And have it look like 

![Imgur](http://i.imgur.com/VWWgxdi.png)

If this is something that you think is cool, I would be happy to make a pull-request. But I couldn't find where a current version of the site is open-sourced (if it is at all).

At the very least, I'd like to maybe have a self-hosted version of the app with this change on it. But it didn't look like where this repo is currently at supported the ability to share/embed.

**Comment by amasad** [comment]
This becomes merely github gists -- I don't believe that adds much value.
