### ISSUE TITLE
Deleting text when typing

### ISSUE THREAD

**Issue by SpookyFlame** [replit/repl.it#185]
When I try to type all it does is replace the character before and any other character I type will just replace that letter. I don't know if it is an issue with my settings, my phone or something else but this issue doesn't occur anywhere else for me. Any help is appreciated.

**Comment by amasad** [comment]
Can you provide your operating system, browser, and any other info that can help us debug this?

**Comment by SpookyFlame** [comment]
Sure, this is on my phone so it is using Android 7.0 and my phone is a Sony Xperia XA and I was using Google Chrome.

**Comment by Jerair** [comment]
I am having this same issue. 
Android 7.0 running mobile Chrome. Phone is the T-Mobile Galaxy Note 5 (USA). 

This prevents me from editing code altogether. I can only input one character per line. It's like the text field immediately deletes a character right when I input one. 
The space bar acts like a backspace key as well. 

Goes like this: 
*type: A
<BACKSPACE>
<INPUT A>

*type: A
<BACKSPACE>

**Comment by Jerair** [comment]
Okay, so it looks like I can't edit my comment on mobile. 
It took my lt;gt symbols as HTML/formatting code. 

Repeated example:
INPUT 'A' 
*BACKSPACE
*'A' APPEARS

INPUT 'B' 
*'A' DELETED
*'B'  TAKES THE PLACE OF 'A' 

INPUT SPACE
*'B' DELETED

**Comment by viethuupham** [comment]
Same issue here on an Android Phone (OnePlus3). Writing or typing is not functioning correctly,  new letters will sometimes overwrite your old letters.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
