### ISSUE TITLE
Incorrect Output (https://repl.it/languages/c)

### ISSUE THREAD

**Issue by xxorr23** [replit/repl.it#186]
#include <string.h>
     #include <stdio.h>
     main(){

      char match[100] = {0x00};
      strcpy(match, "IDFRERFRFCE DSDSFED");
      char status[10];
      char tmp[10];
      printf("match = %s\n", match);
      sscanf(match, "%s %s", tmp, status);
      printf("tmp=%s\n", tmp);
      printf("status=%s", status);
     }

Expected Output:
match = IDFRERFRFCE DSDSFED
tmp=IDFRERFRFCE
status=DSDSFED

Repl.it output:
match = IDFRERFRFCE DSDSFED
tmp=IDFRERFRFCDSDSFED
status=DSDSFED

**Comment by turbio** [comment]
This is expected, the string "IDFRERFRFCE" (length 11) cannot fit into `tmp` (length 10) which leads to undefined behavior.
