### ISSUE TITLE
Incorrect output when running html file

### ISSUE THREAD

**Issue by nakitamccool** [replit/repl.it#187]
When running a html file, I get the following string output (see snap below). I have tested this with a few colleagues who are getting the same result. 
![repl it output](https://user-images.githubusercontent.com/24976693/29268706-dd980a94-80e5-11e7-8f13-150fad649e04.PNG)

**Comment by benjaminEwhite** [comment]
Having same issues.

**Comment by amasad** [comment]
This is fixed. Sorry about that.
