### ISSUE TITLE
Can you support matlab language ?

### ISSUE THREAD

**Issue by xialvjun** [replit/repl.it#194]
just like https://www.coursera.org/learn/machine-learning/supplement/FenyC/addition-and-scalar-multiplication , there is a online sandbox to run matlab language.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
