### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [replit/repl.it#196]
https://insights.stackoverflow.com/survey/2017#most-loved-dreaded-and-wanted

TypeScript is up-and-coming, fancy, and exciting. Can we have support please?

**Comment by amasad** [comment]
yup! soon

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
