### ISSUE TITLE
Bug with fractions

### ISSUE THREAD

**Issue by lagebr** [replit/repl.it#197]
Hi,

I'm using the Python3 Turtle repl, and I it seems that the results I'm getting are not the same as when I run the program on my local IDLE. Here's [the repl.it](https://repl.it/NkBP/2), and the code is as follows.
```import turtle

pelle = turtle.Turtle()

a = (1/4) * 360
print(a)
pelle.right(a)
pelle.forward(100)

turtle.done()
```

The variable `a` gets truncate to zero instead of being 90.

**Comment by amasad** [comment]
Unfortunately it's Python2 so this stupidity is expected behavior in Python2. To make sure it's a float use `(1.0/4)` instead.

**Comment by amasad** [comment]
https://repl.it/NkBP/3

**Comment by lagebr** [comment]
Oh, man. I didn't realize it wasn't Python3. Well, adding that the list of Python2 quirks.
