### ISSUE TITLE
javascript exponential operator misbehaving

### ISSUE THREAD

**Issue by win-chen** [replit/repl.it#200]
Stumbled on some strange behavior with the new exponential operator. I hope this is the place to report it:

console.log((2 ** 2) ** (1/2)) 
evaluates to => 2.665144142690225

It's evaluating properly on node v8.1.4

p.s. love repl.it :D

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
