### ISSUE TITLE
Vim mode hot keys.

### ISSUE THREAD

**Issue by haacki47** [replit/repl.it#203]
Hello! Thank you for adding `vim mode` to repl! It is awesome.
But i would like own keys to enter in vim mode, for now it is `Esc`. But i want to assign it on `d f` like in my IDE

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)
