### ISSUE TITLE
RegEx not working as expected in either node or python

### ISSUE THREAD

**Issue by Norfeldt** [replit/repl.it#204]
I got the following regex: https://regex101.com/r/5uEsJR/4

But somehow it's not working as expected 

https://repl.it/@Norfeldt/NodeMarkDownCleaner

Had similar issue with a python repl...

**Comment by amasad** [comment]
hello, you have windows new lines `\n\r`. Checkout my fork that fixes this: https://repl.it/@amasad/NodeMarkDownCleaner

**Comment by Norfeldt** [comment]
OMG! I used hours trying to figure it out. Thank you so much!

Anything else, String & RegEx related, that is different on Linux that I have to be aware of?

**Comment by amasad** [comment]
not that i'm aware of
