### ISSUE TITLE
'run' action crashes when loading PUBLIC scoped NPM packages (`require('@name/package')`)

### ISSUE THREAD

**Issue by GerHobbelt** [replit/repl.it#208]
See https://repl.it/@GerHobbelt/npmScopedPackagesBug :  

as stated in the code there, run it and see it fail with an repl.it error dialog.

Then comment out the `require(...)` statement of the scoped package (@gerhobbelt/jison-lex) and run again: the code executes without repl.it failure.

The alert says the crash is due to the package not being suitable for browser env, but that is incorrect as this occurs for ANY scoped package: create any scoped package you like, push it into the npm repo (`npm publish --access public`), require() it in repl and observe repl.it FAIL this way.

>
> ## Side Note: 
>
> The package used in the example is one of a group, all of which except one, are scoped packages. 
> The large package which contains ALL the scoped ones PLUS more code to boot is not scoped: 
> `require('jison-gho')` and that one does not trigger this alert/failure message from repl.it. 
> That's one way of saying repl.it got it wrong.
> 
> Another way is that those scoped packages ARE loaded into browser environments elsewhere (using various require()-style loaders) and don't cause trouble there. 
> 
> Having tried other scoped packages with much less and simpler content, they all turn out to crash repl.it.
>

**Comment by timmyichen** [comment]
Hi, sorry - I'm closing this issue because this repo has been deprecated for some time now - suggestions and bug reports should go to https://repl.it/feedback instead - please do me a favor and repost this there?

In case you don't get to this by the time I close issues entirely, here's the markdown of your message so you have it as a reference in your email:

```markdown
See https://repl.it/@GerHobbelt/npmScopedPackagesBug :  

as stated in the code there, run it and see it fail with an repl.it error dialog.

Then comment out the `require(...)` statement of the scoped package (@gerhobbelt/jison-lex) and run again: the code executes without repl.it failure.

The alert says the crash is due to the package not being suitable for browser env, but that is incorrect as this occurs for ANY scoped package: create any scoped package you like, push it into the npm repo (`npm publish --access public`), require() it in repl and observe repl.it FAIL this way.

>
> ## Side Note: 
>
> The package used in the example is one of a group, all of which except one, are scoped packages. 
> The large package which contains ALL the scoped ones PLUS more code to boot is not scoped: 
> `require('jison-gho')` and that one does not trigger this alert/failure message from repl.it. 
> That's one way of saying repl.it got it wrong.
> 
> Another way is that those scoped packages ARE loaded into browser environments elsewhere (using various require()-style loaders) and don't cause trouble there. 
> 
> Having tried other scoped packages with much less and simpler content, they all turn out to crash repl.it.
> 
```

**Comment by amasad** [comment]
I have a quick fix for this. It'll be out later today.
