### ISSUE TITLE
Implement HTML5 app cache

### ISSUE THREAD

**Issue by max99x** [replit/repl.it#40]
There's no technical reason our app can't run offline, so at some point we should implement [HTML5 application cache](http://diveintohtml5.org/offline.html). We should be careful not to make it too big though (e.g. perhaps don't include Ruby/Python libs).

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)
