### ISSUE TITLE
Better vertical screen experience

### ISSUE THREAD

**Issue by aheadley** [replit/repl.it#70]
For tall and narrow screens (i.e. portrait-oriented monitors vs landscape-oriented) it would be nice to have the editor and REPL stacked vertically instead of side by side. Example of what it looks like on a 1080x1920 screen:
http://i.imgur.com/ssKEk1I.png

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)

Also, this has been implemented :)
