### ISSUE TITLE
link to other repls?

### ISSUE THREAD

**Issue by losingkeys** [replit/repl.it#71]
I'm not sure what the criteria are for repls to make it onto this site, but it'd be cool to have [a clojure repl](https://github.com/Raynes/tryclojure), or at least [a link to it online](http://tryclj.com/) somewhere.  Thoughts?

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)
