### ISSUE TITLE
Tutorial on adding new Emscripten-compiled REPL

### ISSUE THREAD

**Issue by tedstrauss** [replit/repl.it#73]
There's a number of issues here asking to add X lang to repl.it.
If you could write a few paragraphs about what the steps are for adding a new language to the interface, assuming it follows the Emscripten compiled approach that I think is used for most of the langs.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)
