### ISSUE TITLE
Editor not available on mobile

### ISSUE THREAD

**Issue by flying-sheep** [replit/repl.it#80]
On my galaxy s2 phone, I only see the REPL, not the editor.

Also there isn’t any UI to switch from one to the other so I guess the editor is either hidden out of sight or disabled.

It would be very useful to expose a switch button or place editor and REPL above each other on tight screens.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)

Also, this has been fixed :)
