### ISSUE TITLE
Opal (Ruby in JavaScript) support

### ISSUE THREAD

**Issue by dtinth** [replit/repl.it#86]
[Opal](http://opalrb.org/) is a Ruby to JavaScript compiler, along with corelib and stdlib.

The compiler itself is written in Ruby, which can be compiled by itself into JavaScript which [can be run in browser (see the demo)](http://opalrb.org/try/).

So I think it would be nice to have Opal in Repl.it as a faster way to run Ruby code.

**Comment by amasad** [comment]
We now have ruby 2 support and it's very fast. However it runs in the server, but we have an API if you're interested http://repl.it/api
