### ISSUE TITLE
Alert JS support

### ISSUE THREAD

**Issue by Sree3** [replit/repl.it#90]
Just wondering if 'alert' was being implemented or if that was left out intentionally.

**Comment by RobertAKARobin** [comment]
Prompt seems to work once, but clicking "Run" subsequent times makes the app hang.

**Comment by amasad** [comment]
cab you paste the code you're using?

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback)

Also, this has been fixed :)
