### ISSUE TITLE
APL unicode characters appear as boxes on Windows

### ISSUE THREAD

**Issue by max99x** [replit/repl.it#92]
The default monospace font on Windows does not cover Unicode. We should switch to one that does. "DejaVu Sans Mono" is a common one that covers almost all the needed characters, but it's still missing a few. Maybe load a custom web font?

**Comment by garudajava** [comment]
Just left a new message about this, noticed it (the boxes) happening under chrome, but not under IE.  

https://github.com/replit/repl.it/issues/134
